//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelClient.HotelService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelModel", Namespace="http://schemas.datacontract.org/2004/07/HotelData")]
    [System.SerializableAttribute()]
    public partial class HotelModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelRating {
            get {
                return this.HotelRatingField;
            }
            set {
                if ((this.HotelRatingField.Equals(value) != true)) {
                    this.HotelRatingField = value;
                    this.RaisePropertyChanged("HotelRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelService.IHotel")]
    public interface IHotel {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/GetAllHotels", ReplyAction="http://tempuri.org/IHotel/GetAllHotelsResponse")]
        HotelClient.HotelService.HotelModel[] GetAllHotels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/GetAllHotels", ReplyAction="http://tempuri.org/IHotel/GetAllHotelsResponse")]
        System.Threading.Tasks.Task<HotelClient.HotelService.HotelModel[]> GetAllHotelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/GetHotelById", ReplyAction="http://tempuri.org/IHotel/GetHotelByIdResponse")]
        HotelClient.HotelService.HotelModel GetHotelById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotel/GetHotelById", ReplyAction="http://tempuri.org/IHotel/GetHotelByIdResponse")]
        System.Threading.Tasks.Task<HotelClient.HotelService.HotelModel> GetHotelByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelChannel : HotelClient.HotelService.IHotel, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelClient : System.ServiceModel.ClientBase<HotelClient.HotelService.IHotel>, HotelClient.HotelService.IHotel {
        
        public HotelClient() {
        }
        
        public HotelClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HotelClient.HotelService.HotelModel[] GetAllHotels() {
            return base.Channel.GetAllHotels();
        }
        
        public System.Threading.Tasks.Task<HotelClient.HotelService.HotelModel[]> GetAllHotelsAsync() {
            return base.Channel.GetAllHotelsAsync();
        }
        
        public HotelClient.HotelService.HotelModel GetHotelById(int id) {
            return base.Channel.GetHotelById(id);
        }
        
        public System.Threading.Tasks.Task<HotelClient.HotelService.HotelModel> GetHotelByIdAsync(int id) {
            return base.Channel.GetHotelByIdAsync(id);
        }
    }
}
